config/routes.rb
Rails.application.routes.draw do
  get 'docomment/commentok'
  devise_for :users
  resources :advertises do
    member do
      get :comment
    end
  end
  get 'home/index'
  # root 'home#index'
  # get 'advertises/homepage'
  root 'advertises#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advertise.rb
class Advertise < ApplicationRecord
    belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :advertise
end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
  before_action :set_advertise, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  # GET /advertises or /advertises.json

  def index
    @advertises = Advertise.all
  end

  # GET /advertises/1 or /advertises/1.json
  def show
  end

  # GET /advertises/new
  def new
    @advertise = Advertise.new
  end

  # GET /advertises/1/edit
  def edit
  end
  
  def comment
  end

  # POST /advertises or /advertises.json
  def create
    @advertise = Advertise.new(advertise_params)

    respond_to do |format|
      if @advertise.save
        format.html { redirect_to @advertise, notice: "Advertise was successfully created." }
        format.json { render :show, status: :created, location: @advertise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertises/1 or /advertises/1.json
  def update
    respond_to do |format|
      if @advertise.update(advertise_params)
        format.html { redirect_to @advertise, notice: "Advertise was successfully updated." }
        format.json { render :show, status: :ok, location: @advertise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @advertise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertises/1 or /advertises/1.json
  def destroy
    @advertise.destroy
    respond_to do |format|
      format.html { redirect_to advertises_url, notice: "Advertise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertise
      @advertise = Advertise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def advertise_params
      params.require(:advertise).permit(:image_urls, :text,:user_id,:Title,:commentbox)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docomment_controller.rb
class DocommentController < ApplicationController
  def commentok
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docomment_helper.rb
module DocommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/advertises/_form.html.erb
  
<%= form_with(model: advertise) do |form| %>
  <% if flag==1 %>
 
  <% if advertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertise.errors.count, "error") %> prohibited this advertise from being saved:</h2>

      <ul>
        <% advertise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :image_urls %>
  <%= form.text_field :image_urls,:maxlength=>"100" %>
</div>
<div class="field">
<%= form.label :Title %>
<%= form.text_field :Title,:maxlength=>"100" %>
</div>

<div class="field">
  <%= form.label :text %>
  <%= form.text_area :text,cols: 100, rows: 15 %>
</div>

<div class="field">
  <%= form.number_field :user_id,id: :advertise_user_id, value:current_user.id, type: :hidden %>
</div>

<div class="field">
<%= form.text_field :commentbox,id: :advertise_commentbox, value:"Comments", type: :hidden %>
</div>
<div class="actions">  
<!--- <input type="submit" name="commit" value="Add Comment" data-disable-with="Update Advertise" /> --->
   <%= form.submit %> 
  </div>

<% else %>

<div class="field">
  <%= form.text_field :image_urls,:maxlength=>"100", type: :hidden %>
</div>

<div class="field">
<%= form.text_field :Title,:maxlength=>"100", type: :hidden %>
</div>

<div class="field" id ='formtext'>
  <%= form.text_field :text,cols: 100, rows: 15, type: :hidden %>
</div>

<div class="field">
  <%= form.number_field :user_id,id: :advertise_user_id, type: :hidden %>
</div>

<div class="field">
<%= form.text_area :commentbox,id: :advertise_commentbox, cols: 40, rows: 4, value:" " %>

</div>

  <div class="actions">  
  <input type="submit" name="commit" value="Add Comment" data-disable-with="Update Advertise" />
  <!--- <%= form.submit %> --->
  </div>
  <% end %>
<% end %>

app/views/advertises/comment.html.erb
<%= form_with(model: advertise) do |form| %>
    <% if advertise.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(advertise.errors.count, "error") %> prohibited this advertise from being saved:</h2>
  
        <ul>
          <% advertise.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
    <%= form.label :image_urls %>
    <%= form.text_field :image_urls,:maxlength=>"100" %>
  </div>
  <div class="field">
  <%= form.label :Title %>
  <%= form.text_field :Title,:maxlength=>"100" %>
  </div>
  
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text,cols: 100, rows: 15 %>
  </div>
  
  <div class="field">
    <%= form.number_field :user_id,id: :advertise_user_id, value:current_user.id, type: :hidden %>
  </div>
  
  <div class="field">
  <%= form.text_field :commentbox,id: :advertise_commentbox, value:"Comments", type: :hidden %>
  </div>
    <div class="actions">
    <script>
    console.log("query page form")
    </script>  
    <%= form.submit %>
    </div>
  <% end %>
  

app/views/advertises/edit.html.erb
<h1>Editing Advertise</h1>

<%= render 'form', advertise: @advertise, flag: 1 %>

<%= link_to 'Show', @advertise %> |
<%= link_to 'Back', advertises_path %>

app/views/advertises/homepage.html.erb
abd

app/views/advertises/homepage.json.erb
json.array! @advertises, partial: "advertises/advertise", as: :advertise

app/views/advertises/index.html.erb
<h1 id='headtag1'></h1>
<p id="notice"><%= notice %></p>
<h1>Advertises</h1>
     <script>
     var counter = 0;
     </script>
    <% @advertises.each do |advertise| %>
        
      <div class="card" style="width: 50%;">
       <img class="card-img-top" src=<%= advertise.image_urls %> alt="Card image cap">
       <div class="card-body">
       <h5 class="card-title"><%= advertise.Title %></h5>
       <p class="card-text"><%= advertise.text %></p>
        <h5 align='right'>BY User : <%= advertise.user_id %></h5>

        <!--- <%= link_to 'Show', advertise, class:"btn btn-primary" %> --->
    <% if user_signed_in? %>
    <% if advertise.user == current_user %>
    <div align = 'right'>
    <%= link_to 'Edit', edit_advertise_path(advertise), class:"btn btn-primary" %>
    <%= link_to 'Delete', advertise, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
    </div>
    <% end %>

       <h5 class="card-title">Comments</h5>
       
       <h6 style="background-color:powderblue;"><%= advertise.commentbox %></h6>
       
       <%= render 'form', advertise: advertise,flag: 0 %>
    

    
    <% end %>
    </div>
</div>
<br>
<br>

    <% end %>
 

<br>

<%= link_to 'New Advertise', new_advertise_path %>

app/views/advertises/new.html.erb
<h1>New Advertise</h1>

<%= render 'form', advertise: @advertise, flag: 1%>

<%= link_to 'Back', advertises_path %>

app/views/advertises/show.html.erb
<!---
<p id="notice"><%= notice %></p>

<p>
  <strong>Image urls:</strong>
  <%= @advertise.image_urls %>
</p>

<p>
  <strong>Text:</strong>
  <%= @advertise.text %>
</p>

<%= link_to 'Edit', edit_advertise_path(@advertise) %> |


--->

<a id='myCheck' href="/advertises"></a>
<script>
 
  
  document.getElementById("myCheck").click();

</script>

app/views/docomment/commentok.html.erb
<h1>Docomment#commentok</h1>
<p>Find me in app/views/docomment/commentok.html.erb</p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
  <%= link_to 'Advertise Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
 
        <li class="nav-item">
        <%= link_to "Create", new_advertise_path, class:"nav-link" %>
        </li>

        
        
        <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path,method: :delete, class:"nav-link" %>
        </li>

       

        <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Advertisement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  
 
  <%= render 'home/header'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class = 'container'>
  <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>












<!DOCTYPE html>
<html>
  <head>
    <title>Advertisement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
  </body>
</html>